[app_server]
is_acme_enabled = false
entrypoint_host = "localhost"
entrypoint_path = "/entrypoint"

[acme_provider]
challenge_type = "http-01"
ca_provider = "letsencrypt"
ca_stage = "staging"
ca_private_key = ""

[nodes]
"example.com" = "entrypoint_example_key_md5_001"
"example.org" = "entrypoint_example_key_md5_002"
