[proxy]
is_acme_enabled = false
entrypoint_host = "localhost"
entrypoint_path = "/"
timeout_request = 3000

[acme]
directory_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
account_url = "" # "https://acme-v02.api.letsencrypt.org/acme/acct/12345678"
contact = [] # ["mailto:someone@example.com"]
eab_kid = "" # "your_eab_kid"
eab_hmac_key = "" # "your_eab_hmac_key"

[node_map]
"entrypoint_example_key_001" = ["example.com"]
"entrypoint_example_key_002" = ["example.org"]
