[proxy]
is_acme_enabled = false
entrypoint_host = "localhost"
entrypoint_path = "/entrypoint"

[acme]
directory_url = "https://acme-staging-v02.api.letsencrypt.org/"
account_key = ""

[node_map]
"example.com" = "entrypoint_example_key_md5_001"
"example.org" = "entrypoint_example_key_md5_002"
